---

# FILE:            {{ role_path }}/tasks/directory/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/file_module.html
# SEE:             https://docs.ansible.com/ansible/latest/modules/win_file_module.html
# SEE:             https://docs.ansible.com/ansible/latest/modules/win_owner_module.html

- name: "apache-virtual-host | draft"
  debug:
    msg: "apache-virtual-host is a draft. Not implemented at this moment"
