---
- name: Converge
  hosts: all
  remote_user: root
  vars:

    faker_groups:
      - name: cdns

    faker_users:
      - name: cdn-site-a
        groups:
          - cdns
      - name: cdn-site-b
        groups:
          - cdns
      - name: site-a
      - name: php-demo
      - name: fititnt
        authorized_key:
          key: https://github.com/fititnt.keys

    # faker_sample_content_static_sites:
    faker_static_sites:
      - dest: /home/site-a/public_html
        owner: site-a
        group: site-a

    # faker_sample_content_cdns:
    faker_cdns:
      - dest: /home/cdn-site-a/public_html
        owner: cdn-site-a
        group: cdns
      - dest: /home/cdn-site-b/public_html
        owner: cdn-site-b
        group: cdns

    # faker_sample_content_phps:
    faker_php_sites:
      - dest: /home/php-demo/public_html
        owner: php-demo

    ## If using devel-nginx AND running on containers without systemd
    ## If using hosts and have have issues to write on /etc/hosts
    # Set faker_isconteiner: true to not make this role try enable a service
    faker_isconteiner: true

  roles:
    - role: ansible-faker

  pre_tasks:
    - name: "Set ISCONTEINER=1"
      shell: "export ISCONTEINER=1"
      changed_when: false # This specific pre_task break Idempotence if not ignored

