---

# FILE:            {{ role_path }}/tasks/users/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/user_module.html
# SEE:             https://docs.ansible.com/ansible/latest/modules/win_user_module.html
# SEE:             https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html

- name: "{{ role_path }}/tasks/user/user.yml"
  include: "{{ role_path }}/tasks/user/user.yml"
  tags:
    - faker-user-user

- name: "{{ role_path }}/tasks/user/authorized_key.yml"
  include: "{{ role_path }}/tasks/user/authorized_key.yml"
  tags:
    - faker-user-authorized-key
